test_task_uptrader/test_task_uptrader/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tree_menu.urls'))]

test_task_uptrader/tree_menu/urls.py
from django.urls import path

from tree_menu import views


app_name = 'tree_menu'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path(
        '<str:item_name>/', views.MenuItemDetailView.as_view(),
        name='item_detail')]

test_task_uptrader/tree_menu/models.py
from django.db import models

from .constans import MENU_TITLE_MAX_LENGTH, MENU_ITEM_NAME_MAX_LENGTH


class Menu(models.Model):
    title = models.CharField(max_length=MENU_TITLE_MAX_LENGTH)

    class Meta:
        verbose_name = 'Меню'
        verbose_name_plural = 'Меню'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.title = self.title.lower()
        self.full_clean()
        super().save(*args, **kwargs)


class MenuItem(models.Model):
    name = models.CharField(max_length=MENU_ITEM_NAME_MAX_LENGTH, unique=True)
    menu = models.ForeignKey(
        Menu, on_delete=models.CASCADE, related_name='items', blank=True)
    parent = models.ForeignKey(
        'self', on_delete=models.CASCADE, null=True, blank=True,
        related_name='childrens')

    class Meta:
        verbose_name = 'Объект меню'
        verbose_name_plural = 'Объекты меню'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.parent:
            self.menu = self.parent.menu
        self.full_clean()
        super().save(*args, **kwargs)

test_task_uptrader/tree_menu/views.py
from typing import Any
from django.views import generic

from .models import MenuItem


class HomeView(generic.TemplateView):
    template_name = 'tree_menu/home.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        return super().get_context_data(**kwargs)


class MenuItemDetailView(generic.DetailView):
    template_name = 'tree_menu/home.html'
    slug_url_kwarg = 'item_name'
    slug_field = 'name'
    model = MenuItem

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        current_item = self.object
        menu_title = current_item.menu.title
        context['active_menu_items'] = {
            menu_title: current_item.name}
        return context

test_task_uptrader/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Мой сайт{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap 5 CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    {% block extra_head %}{% endblock %}
</head>
<body>
    <div class="container-fluid">
        {% block body %}
        {% endblock %}
    </div>
</body>
</html>

test_task_uptrader/templates/tree_menu/home.html
{% extends 'base.html' %}
{% load menu_tags %}
{% block title %}Главная{% endblock %}

{% block body %}
<div class="row min-vh-100">
    <!-- Навигация слева -->
    <nav class="col-md-3 bg-light p-3 border-end">
        {% draw_menu 'main' active_menu_items.main %}
    </nav>

    <!-- Контент справа -->
    <main class="col-md-9 p-4">
        <h1>Добро пожаловать!</h1> {{object.name}}
        <p>Здесь будет основной контент страницы.</p>
        <nav class="col-md-3 bg-light p-3 border-end">
            {% draw_menu 'nav' active_menu_items.nav %}
        </nav>
    </main>
</div>
{% endblock %}

test_task_uptrader/templates/tree_menu/menu.html
<div class="menu">
    <h5 class="mb-3">
      <a href="{% url 'tree_menu:home' %}" class="text-decoration-none">Меню {{menu_title}} </a>
    </h5>
  
    <ul class="list-unstyled">
      {% for parent in parents %}
        <li style="margin-left: {{ forloop.counter0|add:"1" }}0px;">
          <a href="{% url 'tree_menu:item_detail' parent.name %}" class="d-block">
            {{ parent.name }}
          </a>
        </li>
      {% endfor %}
  
      {% if current_obj %}
        <li style="margin-left: {{ parents|length|add:"1" }}0px;" class="fw-bold">
          {{ current_obj.name }}
        </li>
      {% endif %}
  
      {% if childrens %}
        {% for child in childrens %}
          <li style="margin-left: {{ parents|length|add:"2" }}0px;">
            <a href="{% url 'tree_menu:item_detail' child.name %}" class="d-block">
              {{ child.name }}
            </a>
          </li>
        {% endfor %}
      {% endif %}
    </ul>
  </div>
  